
name: Main workflow CI

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:

  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install the dependencies
        run: npm install

      - name: Verify and test
        run: npm test
